theme: jekyll-theme-minimal
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
logo: /assets/img/logo.jpg
description: Didier SEGURA's CV
show_downloads: "true"
github:
  zip_url: https://github.com/didier-segura/digital-cv/cv-didier-segura.pdf
google_analytics: